version: 0.2
env:
  variables:
    SONARQUBE_TOKEN: "8db2d629a779b198b8ae22aad2ceeb47d4072d0d",
    SONARQUBE_HOST: "https://eco-dev-use1-sonarqube.contentservice.net",
    SONARQUBE_PROJECT: "sonar-code-analysis"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum -y update && yum -y upgrade
      - yum install -y jq
  pre_build:
    commands:
      - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
      - yum install -y apache-maven
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - mvn clean verify sonar:sonar -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.host.url=$SONARQUBE_HOST -Dsonar.projectKey=$SONARQUBE_PROJECT
      - sleep 5
      - curl -u $SONARQUBE_TOKEN $SONARQUBE_HOST/api/qualitygates/project_status?projectKey=$SONARQUBE_PROJECT > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
