version: 0.2
env:
  variables:
    LOGIN: "8db2d629a779b198b8ae22aad2ceeb47d4072d0d"
    HOST: "https://eco-dev-use1-sonarqube.contentservice.net"
    Project: "sonar-code-analysis"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum -y update && yum -y upgrade
      - yum install -y jq
      - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
      - yum install -y apache-maven
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - mvn clean verify sonar:sonar -Dsonar.projectKey=$Project -Dsonar.host.url=$HOST -Dsonar.login=$LOGIN
      - sleep 5
      - curl -u $LOGIN $HOST/api/qualitygates/project_status?projectKey=$Project > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
